// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZJjOe13jiX-QgqF8UbeSGRJlcXYHmb2M',
    appId: '1:568727277041:web:588c2929c01d2de1998850',
    messagingSenderId: '568727277041',
    projectId: 'fruit-hub-d3011',
    authDomain: 'fruit-hub-d3011.firebaseapp.com',
    storageBucket: 'fruit-hub-d3011.firebasestorage.app',
    measurementId: 'G-VBL2RNX0BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx49jcgRqu_Rsd7LnDmAg8Hc3FjJdELHg',
    appId: '1:568727277041:android:d15129ca2638171f998850',
    messagingSenderId: '568727277041',
    projectId: 'fruit-hub-d3011',
    storageBucket: 'fruit-hub-d3011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeIjEVnFoYoikjFmI5edukqoJNQomGwhQ',
    appId: '1:568727277041:ios:b4ef63633b9bbb1a998850',
    messagingSenderId: '568727277041',
    projectId: 'fruit-hub-d3011',
    storageBucket: 'fruit-hub-d3011.firebasestorage.app',
    androidClientId: '568727277041-9po135bmrrgngonj66o6jpe4uo62ions.apps.googleusercontent.com',
    iosClientId: '568727277041-m1mlokqfa45e55ne8snfniqfcsigolih.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashBord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeIjEVnFoYoikjFmI5edukqoJNQomGwhQ',
    appId: '1:568727277041:ios:b4ef63633b9bbb1a998850',
    messagingSenderId: '568727277041',
    projectId: 'fruit-hub-d3011',
    storageBucket: 'fruit-hub-d3011.firebasestorage.app',
    androidClientId: '568727277041-9po135bmrrgngonj66o6jpe4uo62ions.apps.googleusercontent.com',
    iosClientId: '568727277041-m1mlokqfa45e55ne8snfniqfcsigolih.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashBord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZJjOe13jiX-QgqF8UbeSGRJlcXYHmb2M',
    appId: '1:568727277041:web:3bc6e15ae8d87435998850',
    messagingSenderId: '568727277041',
    projectId: 'fruit-hub-d3011',
    authDomain: 'fruit-hub-d3011.firebaseapp.com',
    storageBucket: 'fruit-hub-d3011.firebasestorage.app',
    measurementId: 'G-20BHTVX0NB',
  );
}
